import {expect,test} from '@playwright/test'

test('authenticated dashboard and system monitoring expose account views and log controls',async({page})=>{
  const errors=[]
  page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/login')
  expect((await page.request.post('/api/auth/login',{data:{username:'E2E_ONLY',password:'fixture'}})).status()).toBe(200)
  await page.evaluate(()=>sessionStorage.setItem('quant_session_active','1'))
  await page.goto('/')
  await expect(page.locator('.tp-wrap')).toBeVisible()
  await expect(page.getByText('当前使用模拟数据（后端未连接）')).toHaveCount(0)
  await page.screenshot({path:'test-results/feature-dashboard.png',fullPage:true})
  await page.goto('/system')
  await expect(page.locator('.system-page')).toBeVisible()
  await expect(page.locator('.log-viewer')).toBeVisible()
  await page.locator('.log-viewer').getByRole('button',{name:'暂停',exact:true}).click()
  await expect(page.locator('.log-viewer').getByRole('button',{name:'恢复',exact:true})).toBeVisible()
  await page.locator('.log-viewer').getByRole('button',{name:'恢复',exact:true}).click()
  await page.getByPlaceholder('搜索关键词…').fill('NO_SUCH_FIXTURE_LOG')
  await expect(page.locator('.log-count')).toContainText('显示 0')
  await page.screenshot({path:'test-results/feature-system.png',fullPage:true})
  expect((await page.request.post('/api/auth/logout')).status()).toBe(200)
  expect(errors).toEqual([])
})

test('historical chart supports indicator selection drawing clearing fullscreen and PNG export',async({page})=>{
  const errors=[]
  page.on('pageerror',e=>errors.push(e.message))
  await page.addInitScript(()=>localStorage.setItem('quant_cur_symbol',JSON.stringify({symbol:'E2E2026',name:'功能测试样本',exchange:'TEST'})))
  await page.goto('/watch')
  await expect(page.locator('.chart-dom canvas').first()).toBeVisible()
  const toolbar=page.locator('.kline-toolbar')
  await toolbar.locator('.toolbar-right > .el-select').click()
  await page.getByRole('option',{name:'RSI',exact:true}).click()
  await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('quant_indicator_active')))).toBe('rsi')
  await toolbar.getByRole('button',{name:'均线',exact:true}).click()
  await page.locator('.ma-panel .ma-row').first().locator('.el-switch').click()
  await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('quant_indicator_ma'))[0].visible)).toBe(false)
  await toolbar.getByRole('button',{name:'均线',exact:true}).click()
  await page.reload()
  await expect(page.locator('.chart-dom canvas').first()).toBeVisible()
  await expect(toolbar.locator('.toolbar-right > .el-select')).toContainText('RSI')
  await toolbar.locator('.draw-tools .draw-btn').nth(2).click()
  const box=await page.locator('.chart-dom').boundingBox()
  await page.mouse.click(box.x+box.width*.55,box.y+box.height*.25)
  await expect(toolbar.locator('.draw-tools .draw-btn')).toHaveCount(5)
  const graphicCount=()=>page.evaluate(async()=>{
    const {getInstanceByDom}=await import('/src/utils/echarts.js')
    const graphics=getInstanceByDom(document.querySelector('.chart-dom')).getOption().graphic||[]
    return graphics.reduce((total,component)=>total+(component.elements?.length||0),0)
  })
  await expect.poll(graphicCount).toBe(2)
  await toolbar.locator('.draw-tools .draw-btn').last().click()
  await expect(toolbar.locator('.draw-tools .draw-btn')).toHaveCount(4)
  await expect.poll(graphicCount).toBe(0)
  const iconButtons=toolbar.locator('.toolbar-right > button.icon-btn')
  const downloadPromise=page.waitForEvent('download')
  await iconButtons.nth(1).click()
  const download=await downloadPromise
  expect(download.suggestedFilename()).toMatch(/^kline_E2E2026_1d_\d+\.png$/)
  expect(await download.failure()).toBeNull()
  await iconButtons.nth(0).click()
  await expect.poll(()=>page.evaluate(()=>Boolean(document.fullscreenElement))).toBe(true)
  await iconButtons.nth(0).click()
  await expect.poll(()=>page.evaluate(()=>Boolean(document.fullscreenElement))).toBe(false)
  await page.screenshot({path:'test-results/feature-chart.png',fullPage:true})
  expect(errors).toEqual([])
})

test('unsupported custom chart period is reported instead of showing fabricated bars',async({page})=>{
  await page.addInitScript(()=>localStorage.setItem('quant_cur_symbol',JSON.stringify({symbol:'E2E2026',name:'功能测试样本',exchange:'TEST'})))
  await page.goto('/watch')
  await expect(page.locator('.chart-dom canvas').first()).toBeVisible()
  await page.locator('.custom-period input').first().fill('7')
  const response=page.waitForResponse(r=>r.url().includes('/api/watch/kline?')&&r.url().includes('interval=7d'))
  await page.locator('.custom-period').getByRole('button',{name:'确认',exact:true}).click()
  expect((await response).status()).toBe(400)
  await expect(page.locator('.chart-error')).toBeVisible()
})
